jobs:
  - name: "Disable telemetry services"
    description: "Disables various telemetry services and tasks"
    steps:

    - name: "Stop Telemetry Services"
      service:
        stop:
          - DiagTrack
          - dmwappushservice
          - DcpSvc
        disable:
          - DiagTrack
          - dmwappushservice
          - DcpSvc

    - name: "Disable WiFi Sense and Hotspot Reporting"
      registry:
        entries:
          - hive: HKLM
            path: Software\Microsoft\PolicyManager\default\WiFi
            add:
              AllowAutoConnectToWiFiSenseHotspots: { type: DWord, value: 0 }
              AllowWiFiHotSpotReporting: { type: DWord, value: 0 }

    - name: "Disable AppCompat Engine"
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Policies\Microsoft\Windows\AppCompat
            add:
              DisableEngine: { type: DWord, value: 1 }
              SbEnable: { type: DWord, value: 0 }
              DisablePCA: { type: DWord, value: 1 }

    - name: "Disable AppCompat Engine (Wow6432)"
      condition:
        bitness: x64
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\AppCompat
            add:
              DisableEngine: { type: DWord, value: 1 }
              SbEnable: { type: DWord, value: 0 }
              DisablePCA: { type: DWord, value: 1 }

    - name: "Disable User Activity Publishing"
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Policies\Microsoft\Windows\System
            add:
              PublishUserActivities: { type: DWord, value: 0 }

    - name: "Disable CEIP"
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Policies\Microsoft\SQMClient\Windows
            add:
              CEIPEnable: { type: DWord, value: 0 }

    - name: "Disable AppCompat Telemetry and Inventory"
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Policies\Microsoft\Windows\AppCompat
            add:
              AITEnable: { type: DWord, value: 0 }
              DisableInventory: { type: DWord, value: 1 }
              DisablePCA: { type: DWord, value: 1 }
              DisableUAR: { type: DWord, value: 1 }

    - name: "Prevent Device Metadata from Network"
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Microsoft\Windows\CurrentVersion\Device Metadata
            add:
              PreventDeviceMetadataFromNetwork: { type: DWord, value: 1 }

    - name: "Disable SQM Logger"
      registry:
        entries:
          - hive: HKLM
            path: SYSTEM\CurrentControlSet\Control\WMI\AutoLogger\SQMLogger
            add:
              Start: { type: DWord, value: 0 }

    - name: "Disable Experimentation"
      registry:
        entries:
          - hive: HKLM
            path: SOFTWARE\Microsoft\PolicyManager\current\device\System
            add:
              AllowExperimentation: { type: DWord, value: 0 }

    - name: "Deny telemetry processes"
      processControl:
        deny:
        - CompatTelRunner.exe
        - DeviceCensus.exe

    - name: "Restrict access to Diagnosis Auto Logger folder"
      exec:
        type: cmd
        commands:
          - 'icacls "C:\ProgramData\Microsoft\Diagnosis" /deny SYSTEM:(OI)(CI)F'

    - name: "Disable Customer Experience and related scheduled tasks"
      exec:
        type: cmd
        commands:
          - 'schtasks /end /tn "\Microsoft\Windows\Customer Experience Improvement Program\Consolidator"'
          - 'schtasks /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\Consolidator" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Customer Experience Improvement Program\BthSQM"'
          - 'schtasks /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\BthSQM" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask"'
          - 'schtasks /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip"'
          - 'schtasks /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Customer Experience Improvement Program\Uploader"'
          - 'schtasks /change /tn "\Microsoft\Windows\Customer Experience Improvement Program\Uploader" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser"'
          - 'schtasks /change /tn "\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Application Experience\ProgramDataUpdater"'
          - 'schtasks /change /tn "\Microsoft\Windows\Application Experience\ProgramDataUpdater" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Application Experience\StartupAppTask"'
          - 'schtasks /change /tn "\Microsoft\Windows\Application Experience\StartupAppTask" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector"'
          - 'schtasks /change /tn "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticResolver"'
          - 'schtasks /change /tn "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticResolver" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem"'
          - 'schtasks /change /tn "\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Shell\FamilySafetyMonitor"'
          - 'schtasks /change /tn "\Microsoft\Windows\Shell\FamilySafetyMonitor" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Shell\FamilySafetyRefresh"'
          - 'schtasks /change /tn "\Microsoft\Windows\Shell\FamilySafetyRefresh" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Shell\FamilySafetyUpload"'
          - 'schtasks /change /tn "\Microsoft\Windows\Shell\FamilySafetyUpload" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Autochk\Proxy"'
          - 'schtasks /change /tn "\Microsoft\Windows\Autochk\Proxy" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Maintenance\WinSAT"'
          - 'schtasks /change /tn "\Microsoft\Windows\Maintenance\WinSAT" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Application Experience\AitAgent"'
          - 'schtasks /change /tn "\Microsoft\Windows\Application Experience\AitAgent" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Windows Error Reporting\QueueReporting"'
          - 'schtasks /change /tn "\Microsoft\Windows\Windows Error Reporting\QueueReporting" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\CloudExperienceHost\CreateObjectTask"'
          - 'schtasks /change /tn "\Microsoft\Windows\CloudExperienceHost\CreateObjectTask" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\DiskFootprint\Diagnostics"'
          - 'schtasks /change /tn "\Microsoft\Windows\DiskFootprint\Diagnostics" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\FileHistory\File History (maintenance mode)"'
          - 'schtasks /change /tn "\Microsoft\Windows\FileHistory\File History (maintenance mode)" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\PI\Sqm-Tasks"'
          - 'schtasks /change /tn "\Microsoft\Windows\PI\Sqm-Tasks" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\NetTrace\GatherNetworkInfo"'
          - 'schtasks /change /tn "\Microsoft\Windows\NetTrace\GatherNetworkInfo" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\AppID\SmartScreenSpecific"'
          - 'schtasks /change /tn "\Microsoft\Windows\AppID\SmartScreenSpecific" /disable'
          - 'schtasks /change /tn "\Microsoft\Windows\WindowsUpdate\Automatic App Update" /disable'
          - 'schtasks /change /tn "\Microsoft\Windows\Time Synchronization\ForceSynchronizeTime" /disable'
          - 'schtasks /change /tn "\Microsoft\Windows\Time Synchronization\SynchronizeTime" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\HelloFace\FODCleanupTask"'
          - 'schtasks /change /tn "\Microsoft\Windows\HelloFace\FODCleanupTask" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Feedback\Siuf\DmClient"'
          - 'schtasks /change /tn "\Microsoft\Windows\Feedback\Siuf\DmClient" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload"'
          - 'schtasks /change /tn "\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Application Experience\PcaPatchDbTask"'
          - 'schtasks /change /tn "\Microsoft\Windows\Application Experience\PcaPatchDbTask" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Device Information\Device"'
          - 'schtasks /change /tn "\Microsoft\Windows\Device Information\Device" /disable'
          - 'schtasks /end /tn "\Microsoft\Windows\Device Information\Device User"'
          - 'schtasks /change /tn "\Microsoft\Windows\Device Information\Device User" /disable'